import { lazy } from "preact/compat";
const First = lazy(() => import("./categories/1DBTypes"));
const Second = lazy(() => import("./categories/2DBModeling"));
const Third = lazy(() => import("./categories/3Scaling"));
const Fourth = lazy(() => import("./categories/4Messaging"));
const Fifth = lazy(() => import("./categories/5DBRelication"));
const Sixth = lazy(() => import("./categories/6LoadBalancing"));
const Seven = lazy(() => import("./categories/7StateLessandfull"));
const Eight = lazy(() => import("./categories/8LoadInStateFull"));
const Nine = lazy(() => import("./categories/9Sharding"));
const Ten = lazy(() => import("./categories/10Hashing"));
const Eleven = lazy(() => import("./categories/11ConsistentHashing"));
const Tweleve = lazy(() => import("./categories/12Cap"));
const Thirteen = lazy(() => import("./categories/13QA1"));
const  Fourteen= lazy(() => import("./categories/14QA2"));
const Home = lazy(() => import("./Home"));
import Navbar from "./Navbar/Navbar";
import Loading from "./Common/Loading";
export { Loading,Fourteen, Navbar, Home, First, Second, Third, Fourth, Fifth, Sixth, Seven, Eight, Nine, Eleven, Tweleve, Thirteen, Ten };
